app:
  datasource:
    jdbc-url: jdbc:postgresql://209.97.142.151:5432/
    username: postgres
    password: COS301-DsP
    pool-size: 30

---

validators:
  emailRegex: "^(.+)@(.+)$"
  passwordRegex: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$"
  contactRegex: "^[0-9]{10,10}$"